import { ChevronRight, Search } from 'lucide-react'
import { useState } from 'react'
import { Badge, Empty, FieldLabel, Spinner } from '../components'
import type { Project, SearchHit, Source } from '../types'

export function SearchPage({query,setQuery,hits,projects,sources,loading,onSearch,onSelect}: {query:string;setQuery:(v:string)=>void;hits:SearchHit[];projects:Project[];sources:Source[];loading:boolean;onSearch:(filters:{project:string;mount:string;kind:string})=>void;onSelect:(id:string)=>void}) {
  const [project,setProject]=useState(''),[mount,setMount]=useState(''),[kind,setKind]=useState(''); const filters={project,mount,kind}
  return <div className="space-y-6"><div className="flex gap-3"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input className="search-input" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&onSearch(filters)} placeholder="搜索工作记忆"/></div><button className="button button-primary" onClick={()=>onSearch(filters)}>{loading?<Spinner label="搜索中"/>:'搜索'}</button></div><div className="grid gap-3 sm:grid-cols-3"><div><FieldLabel>项目</FieldLabel><select className="select" value={project} onChange={e=>setProject(e.target.value)}><option value="">全部项目</option>{projects.map(p=><option value={p.id} key={p.id}>{p.id}</option>)}</select></div><div><FieldLabel>挂载点</FieldLabel><select className="select" value={mount} onChange={e=>setMount(e.target.value)}><option value="">全部挂载点</option>{sources.filter(s=>s.enabled&&(!project||s.projectId===project)).map(s=><option value={s.id} key={s.id}>{s.mountName||s.id}</option>)}</select></div><div><FieldLabel>类型</FieldLabel><select className="select" value={kind} onChange={e=>setKind(e.target.value)}><option value="">全部类型</option>{['conclusion','decision','correction','verification','todo','document'].map(k=><option key={k}>{k}</option>)}</select></div></div>{hits.length===0?<Empty title="输入关键词开始检索" detail="可以按项目、挂载点和记忆类型缩小范围"/>:<div className="divide-y divide-slate-200 border-y border-slate-200">{hits.map(hit=><button className="result-row" key={hit.unit.id} onClick={()=>onSelect(hit.unit.id)}><div className="min-w-0 flex-1 text-left"><div className="mb-2 flex items-center gap-2"><Badge tone={hit.unit.kind==='correction'?'warning':'neutral'}>{hit.unit.kind}</Badge><span className="truncate font-medium">{hit.unit.title}</span></div><p className="line-clamp-2 text-sm leading-6 text-slate-500">{hit.unit.content}</p><div className="mt-2 text-xs text-slate-400">{hit.unit.sourceId} · {new Date(hit.unit.occurredAt).toLocaleString()}</div></div><ChevronRight size={17} className="shrink-0 text-slate-300"/></button>)}</div>}</div>
}
