import { useCallback, useEffect, useMemo, useState } from 'react'
import { BookOpen, Database, LayoutDashboard, RefreshCw, Search, Settings2, X } from 'lucide-react'
import { api } from './api'
import { Badge, Notice } from './components'
import { ConfigPage } from './pages/ConfigPage'
import { Dashboard } from './pages/Dashboard'
import { IndexPage } from './pages/IndexPage'
import { SearchPage } from './pages/SearchPage'
import { SourcesPage } from './pages/SourcesPage'
import type { ConfigData, MemoryRecord, Project, RegistryAction, SearchHit, Source, Status, SyncRun } from './types'

const nav=[{id:'dashboard',label:'总览',icon:LayoutDashboard},{id:'search',label:'记忆搜索',icon:Search},{id:'sources',label:'数据与同步',icon:BookOpen},{id:'config',label:'配置管理',icon:Settings2},{id:'index',label:'索引管理',icon:Database}]

export default function App(){
  const [page,setPage]=useState('dashboard'),[status,setStatus]=useState<Status|null>(null),[projects,setProjects]=useState<Project[]>([]),[sources,setSources]=useState<Source[]>([]),[runs,setRuns]=useState<SyncRun[]>([])
  const [query,setQuery]=useState(''),[hits,setHits]=useState<SearchHit[]>([]),[memory,setMemory]=useState<MemoryRecord|null>(null),[searching,setSearching]=useState(false)
  const [config,setConfig]=useState<ConfigData|null>(null),[raw,setRaw]=useState(''),[actions,setActions]=useState<RegistryAction[]>([]),[busy,setBusy]=useState(''),[notice,setNotice]=useState<{kind:'success'|'error';text:string}|null>(null)
  const title=useMemo(()=>nav.find(n=>n.id===page)?.label??'详情',[page])
  const load=useCallback(async(silent=false)=>{try{const [s,p,src,r]=await Promise.all([api.status(),api.projects(),api.sources(),api.runs()]);setStatus(s);setProjects(p);setSources(src);setRuns(r)}catch(e){if(!silent)setNotice({kind:'error',text:(e as Error).message})}},[])
  useEffect(()=>{load();const timer=setInterval(()=>load(true),10000);return()=>clearInterval(timer)},[load])
  useEffect(()=>{if(page==='config'&&!config)api.config().then(c=>{setConfig(c);setRaw(c.raw);setActions(c.actions)}).catch(e=>setNotice({kind:'error',text:e.message}))},[page,config])
  const search=async(filters:{project:string;mount:string;kind:string})=>{if(!query.trim())return;setSearching(true);try{const params=new URLSearchParams({q:query});if(filters.project)params.set('project',filters.project);if(filters.mount)params.set('mount',filters.mount);if(filters.kind)params.set('kind',filters.kind);setHits(await api.search(params))}catch(e){setNotice({kind:'error',text:(e as Error).message})}finally{setSearching(false)}}
  const selectMemory=async(id:string)=>{try{setMemory(await api.memory(id))}catch(e){setNotice({kind:'error',text:(e as Error).message})}}
  const sync=async(id?:string)=>{setBusy(id||'all');try{await api.sync(id);setNotice({kind:'success',text:id?`已同步 ${id}`:'全部数据来源同步完成'});await load(true)}catch(e){setNotice({kind:'error',text:(e as Error).message})}finally{setBusy('')}}
  const validate=async()=>{setBusy('validate');try{const result=await api.validateConfig(raw);setActions(result.actions);setNotice({kind:'success',text:result.actions.length?`配置有效，检测到 ${result.actions.length} 项变更`:'配置有效，运行状态已一致'})}catch(e){setNotice({kind:'error',text:(e as Error).message})}finally{setBusy('')}}
  const save=async()=>{if(!config)return;setBusy('save');try{await api.saveConfig(raw,config.hash);const current=await api.config();setConfig(current);setRaw(current.raw);setActions(current.actions);setNotice({kind:'success',text:'配置已原子保存并自动应用'});await load(true)}catch(e){setNotice({kind:'error',text:(e as Error).message})}finally{setBusy('')}}
  const rebuild=async()=>{setBusy('rebuild');try{const result=await api.rebuild();setNotice({kind:'success',text:`已重建 ${result.documents} 条索引记录`});await load(true)}catch(e){setNotice({kind:'error',text:(e as Error).message})}finally{setBusy('')}}
  return <div className="min-h-screen bg-[#f7f8fa] pb-20 text-slate-900 md:pb-0"><aside className="fixed inset-y-0 left-0 z-20 hidden w-60 flex-col border-r border-slate-200 bg-white px-4 py-5 md:flex"><Brand/><nav className="space-y-1">{nav.map(item=><NavItem key={item.id} item={item} active={page===item.id} onClick={()=>setPage(item.id)}/>)}</nav><div className="mt-auto border-t border-slate-100 pt-4"><div className="flex items-center gap-2 px-2 text-xs text-slate-500"><span className={`size-2 rounded-full ${status?.backend==='available'?'bg-emerald-500':'bg-amber-400'}`}/>{status?.backend==='available'?'运行正常':'后端异常'}</div></div></aside><main className="min-h-screen md:ml-60"><header className="sticky top-0 z-10 flex h-16 items-center justify-between border-b border-slate-200 bg-[#f7f8fa]/95 px-5 backdrop-blur md:px-10"><div><div className="text-xs font-medium text-slate-400">工作记忆</div><h1 className="text-lg font-semibold">{title}</h1></div><button className="icon-button" title="刷新" onClick={()=>load()}><RefreshCw size={17}/></button></header><div className="mx-auto max-w-6xl px-5 py-6 md:px-10 md:py-8">{notice&&<div className="mb-5"><Notice kind={notice.kind} close={()=>setNotice(null)}>{notice.text}</Notice></div>}{page==='dashboard'&&<Dashboard status={status} runs={runs} onSearch={q=>{setQuery(q);setPage('search')}}/>}{page==='search'&&<SearchPage query={query} setQuery={setQuery} hits={hits} projects={projects} sources={sources} loading={searching} onSearch={search} onSelect={selectMemory}/>} {page==='sources'&&<SourcesPage sources={sources} runs={runs} busy={busy} onSync={sync}/>} {page==='config'&&<ConfigPage data={config} sources={sources} raw={raw} setRaw={setRaw} actions={actions} busy={busy} onValidate={validate} onSave={save}/>} {page==='index'&&<IndexPage status={status} busy={busy==='rebuild'} onRebuild={rebuild}/>}</div></main><nav className="fixed inset-x-0 bottom-0 z-20 grid grid-cols-5 border-t border-slate-200 bg-white md:hidden">{nav.map(item=><NavItem key={item.id} item={item} active={page===item.id} mobile onClick={()=>setPage(item.id)}/>)}</nav>{memory&&<MemoryDrawer record={memory} close={()=>setMemory(null)}/>}</div>
}

function Brand(){return <div className="mb-8 flex items-center gap-3 px-2"><div className="grid size-9 place-items-center rounded-lg bg-slate-900 text-sm font-bold text-white">oh</div><div><div className="font-semibold">ohyeah</div><div className="text-xs text-slate-400">工作记忆服务</div></div></div>}
function NavItem({item,active,onClick,mobile=false}:{item:typeof nav[number];active:boolean;onClick:()=>void;mobile?:boolean}){const Icon=item.icon;return <button onClick={onClick} className={mobile?`flex h-16 flex-col items-center justify-center gap-1 text-[10px] ${active?'text-slate-900':'text-slate-400'}`:`nav-item ${active?'nav-active':''}`}><Icon size={mobile?17:16}/><span>{item.label}</span></button>}
function MemoryDrawer({record,close}:{record:MemoryRecord;close:()=>void}){const m=record.unit;return <div className="fixed inset-0 z-30 bg-slate-900/15" onClick={close}><article className="absolute inset-y-0 right-0 w-[min(640px,100vw)] overflow-y-auto border-l border-slate-200 bg-white p-6 shadow-2xl md:p-9" onClick={e=>e.stopPropagation()}><div className="mb-8 flex items-center justify-between"><Badge tone={m.kind==='correction'?'warning':'neutral'}>{m.kind}</Badge><button className="icon-button" onClick={close} title="关闭"><X size={18}/></button></div><h2 className="text-2xl font-semibold leading-tight">{m.title}</h2><div className="mt-3 text-xs text-slate-400">{new Date(m.occurredAt).toLocaleString()} · {m.status}</div><div className="mt-8 whitespace-pre-wrap text-[15px] leading-8 text-slate-700">{m.content}</div><dl className="mt-10 grid gap-4 border-t border-slate-200 pt-6 text-sm"><Meta label="来源" value={`${m.sourceType} · ${m.sourceId}`}/>{m.path&&<Meta label="路径" value={m.path}/>} {m.threadId&&<Meta label="会话" value={m.threadId}/>} {Object.entries(record.reference||{}).map(([k,v])=><Meta key={k} label={k} value={v}/>)}</dl></article></div>}
function Meta({label,value}:{label:string;value:string}){return <div><dt className="mb-1 text-xs text-slate-400">{label}</dt><dd className="break-all text-slate-700">{value}</dd></div>}
